# Default values for hyperglance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# EFS storage [REQUIRED]

efs:
  filesystem_id: fs-xxxx
  postgresql:
    accesspoint_id: fsap-xxxx
  hyperglance:
    accesspoint_id: fsap-xxxx

# Load balancer certificate - [REQUIRED]
albCertificateArn: arn:aws:acm:xxxx

# K8 service account
serviceAccount:
  name: hyperglance
  iamRole: arn:aws:iam::xxxx # IAM role ARN the K8 service account will use to auth against AWS

# Container resource constraints
resources:
  postgresql:
    requests:
      memory: "2Gi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "1000m"
  httpd:
    requests:
      memory: "500Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  wildfly:
    requests:
      memory: "4Gi"
      cpu: "500m"
    limits:
      memory: "8Gi"
      cpu: "2000m"

# Container Images
imagePullPolicy: Always
restartPolicy: Always

install:
  image: busybox
  tag: latest

postgresql:
  image: hyperglance/postgresql
  tag: latest

httpd:
  image: hyperglance/httpd
  tag: latest

wildfly:
  image: hyperglance/wildfly
  tag: latest


# Hyperglance HTTPD Service
service:
  type: NodePort

servicehttps:
  port: 443


# Config Map
samlEnabled: false
MAX_HEAPSIZE: '4096m' # Wildfly heap size setting - adjust accordingly
RUNNING_IN: 'AWS' # Set to 'AWS' to enable K8 service account and IAM role assumption in Hyperglance

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false