---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyperglance-data
  labels:
    app: hyperglance
spec:
   capacity:
      storage: 20Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: efs-sc
   claimRef:
      name: hyperglance-data
      namespace: hyperglance
   csi:
      driver: efs.csi.aws.com
      volumeHandle: <EFS_Filesystem_ID>::<EFS_Accesspoint_ID> # [REQUIRED] Set these values for your deployment fs-075969c3793a0ce8d::fsap-0d583b9784be5fb4c

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  labels:
    app: hyperglance
spec:
   capacity:
      storage: 20Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: efs-sc
   claimRef:
      name: hyperglance-postgresql-data
      namespace: hyperglance
   csi:
      driver: efs.csi.aws.com
      volumeHandle: <EFS_Filesystem_ID>::<EFS_Accesspoint_ID> # [REQUIRED] Set these values for your deployment e.g. fs-075969c3793a0ce8d::fsap-07f5c973018d10062

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperglance-postgresql-data
  labels:
    app: hyperglance
spec:
  storageClassName: efs-sc
  volumeName: postgresql-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperglance-data
  labels:
    app: hyperglance
spec:
  storageClassName: efs-sc
  volumeName: hyperglance-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi