---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
   capacity:
      storage: 20Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: efs-sc
   claimRef:
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-data
   csi:
      driver: efs.csi.aws.com
      volumeHandle: {{ printf "%s::%s" $.Values.efs.filesystem_id $.Values.efs.hyperglance.accesspoint_id | quote }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgresql-data
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
   capacity:
      storage: 20Gi
   volumeMode: Filesystem
   accessModes:
      - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: efs-sc
   claimRef:
      namespace: {{ .Release.Namespace }}
      name: {{ .Release.Name }}-postgresql-data
   csi:
      driver: efs.csi.aws.com
      volumeHandle: {{ printf "%s::%s" $.Values.efs.filesystem_id $.Values.efs.postgresql.accesspoint_id | quote }}