apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-httpd-ssl"
  labels:
    app: {{ template "hyperglance.name" . }}
    chart: {{ template "hyperglance.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
  hyperglance.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDVDCCAjygAwIBAgIJAI/kNmmHcVLKMA0GCSqGSIb3DQEBCwUAMFExFDASBgNV
    BAMMC0h5cGVyZ2xhbmNlMRkwFwYDVQQKDBBIeXBlcmdsYW5jZSBJbmMuMREwDwYD
    VQQHDAhTYW4gSm9zZTELMAkGA1UEBhMCVVMwHhcNMjAxMDI5MTIyNjI5WhcNMjEx
    MTIzMTIyNjI5WjBRMRQwEgYDVQQDDAtIeXBlcmdsYW5jZTEZMBcGA1UECgwQSHlw
    ZXJnbGFuY2UgSW5jLjERMA8GA1UEBwwIU2FuIEpvc2UxCzAJBgNVBAYTAlVTMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs5/jnRTs8a2jjlvOFzq9HyD1
    WiMqkA9T/PZB+otf8k16ts5ghd0fRzLQQX9uTV/ewKoIHENYFWURhzPmrEFbYYAb
    f6pkq0nv4dl7ifCiSsg1bIGnq5ZeWXmgOT9r4j1BRmXF4sztLSVcpkFi6h/3DebU
    0T+vb/umwTHOnRIfb2nRnGabzVRI5JkIGdGQZaHahx3OPV9fIareKdsdiysy0fWD
    DULmnZTXcTzxzc62cJG0aye719f9i0Yc+uhEel377vceG7V7qEr8xmrtpUFUrsF6
    BW69jljJgocu0OnfrHHLL9ZH1tZW36f8P/bP72cQk3169nXFDOpGfKoLUdjfPQID
    AQABoy8wLTAWBgNVHREEDzANggtIeXBlcmdsYW5jZTATBgNVHSUEDDAKBggrBgEF
    BQcDATANBgkqhkiG9w0BAQsFAAOCAQEACOyJoCXQNHld/Feba433mq39a+CR1rqX
    KIF8EusJshQSn1rFIU5khhnmOQMAOb2xFpp5656nFA/fsMXvsUzDlNm0G3NdGERG
    svqwpfHPFtQdyjwFtV8CmPB/DacJgc5PGuYuVm8JzYa2SleqQl0ehw9r38F87ktV
    Ycdg0ykAVphT+d2CknH+MXBXpQRpG1KGiL1EKOqvay4fgFFklHpG2NxLNMC4eCCf
    XE71KPpeNy5sXH24j0c5eFmfIJ+Ce+CdMxvlQvOU0WB6pNfzwo80n7Gv8HZJcvBk
    Uik8Pm8rGh65JyaXkpp4AeOZpoeDYjht7DFF344WUu0T6+D/s4jz+A==
    -----END CERTIFICATE-----

  hyperglance.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCzn+OdFOzxraOO
    W84XOr0fIPVaIyqQD1P89kH6i1/yTXq2zmCF3R9HMtBBf25NX97AqggcQ1gVZRGH
    M+asQVthgBt/qmSrSe/h2XuJ8KJKyDVsgaerll5ZeaA5P2viPUFGZcXizO0tJVym
    QWLqH/cN5tTRP69v+6bBMc6dEh9vadGcZpvNVEjkmQgZ0ZBlodqHHc49X18hqt4p
    2x2LKzLR9YMNQuadlNdxPPHNzrZwkbRrJ7vX1/2LRhz66ER6Xfvu9x4btXuoSvzG
    au2lQVSuwXoFbr2OWMmChy7Q6d+sccsv1kfW1lbfp/w/9s/vZxCTfXr2dcUM6kZ8
    qgtR2N89AgMBAAECggEAPPSlaUkQn3MtbcH5zihAxa+Jk20bpIePGOj4uu1RQgjI
    /ABNASBo3OCBi7iS1e8SyI7q8axo19nUeO1D+nCzcgLnUgug3f/ZR+tl4QmoCXin
    qIrXO4NrwTFlDghXtA7Vd+5RmQWx9wAW0NSfnJP8YttSnS/feUEM9cLROrxLrqLI
    rYl/ACVrpsbgQ07sqm70/gXQiqvVO0+1hflsWLTKob0t3GEWXDnSUZPXDo4qvx0d
    57P8rpMworp1cyCqHLsqbAVlqz7QxkY40qUiJSQTCcJh/1pazaACHmaVm4dgpocm
    pCieQkFkrfGiBmU4YIm3PD1gTYX4mHylbMAiREP8AQKBgQDgd9vnnsCylkGITbsJ
    kvixEHzNiJ72JiXhtJ7d32kdHWB04DL1t2zVIm99xiyIIvtehGZh2+OlrKFzf0oE
    Y2Sy1zzWz/2HuL9r1GuxC0olEXSb6zWCpUSVuXwHYJdGsB1I1nZeV4BxucmBs/PM
    WSs+3OpyXmpGyn/a+polp1xE6QKBgQDM22Z2MF4KkA/1jO0WjdSiIZnWKBXeCLkY
    8HV/7DSaDOUs0qVGBIrtLlE4stqdY/c+o+D6jaLysNc3I7KKhoWK8ZsiRQlnK1Id
    XfIa9reNYh5SHHnCAFgqOgaA7B8Sv3adG69yZY4sD+E93JiTiyjCit9SIzULuMdE
    WvQZLwTjNQKBgGdeSuJq9QpIr3z5bryF9gh0M0TjOXDZOHCsIMzD6UADGzw3UsBc
    671q0jT1YeR/V4q7JfrCrB7LVL4/S/KhYuoIvHef6Hzr0xrxA3bQYCCZ3T1AH7A+
    M0tP05ICJSfkSlgUiwX+/aNhjy4vlIHyPjwAt+ZbHE3lSuOoq/vTCmahAoGAClCx
    5BmjYpzGcPLbrVsO7esLOAFkuH1v9JWHFR3ruCYWFB+3OsNXy4GdjWFUKMCz3m+a
    EIO5RMcqzxf5EYiciNaJnTwksRE5XUkxu7HYpEHgjPnqF5600cuCMFOzbNo/OsH+
    H6CFfCqAiQDmnedP8hvUCurC7Qgs4IBD8lCvylECgYEAqQPEEP/3iPVh+HAqLn3X
    CbZ0YOgZsE9QFmJCYmkF4f/g91PchuvV2T7ZoKqOyL+uu6z0OeoSznungujFPtSb
    MDdKyiZ79TCgFvFY5p8EZaVOKGmXVw5DOBjdfAJepG/rrgu8uIWi4MoVASqED34U
    Z2R6WaUqf1v+UMjqc404G/w=
    -----END PRIVATE KEY-----